# Generated by Django 4.2.23 on 2026-01-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trapickapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processingprofile',
            name='config_parameters',
        ),
        migrations.RemoveField(
            model_name='processingprofile',
            name='counting_direction',
        ),
        migrations.RemoveField(
            model_name='processingprofile',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='processingprofile',
            name='congestion_threshold',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='processingprofile',
            name='detector_type',
            field=models.CharField(choices=[('vertical_top_bottom', 'Vertical Top→Bottom'), ('vertical_bottom_top', 'Vertical Bottom→Top'), ('horizontal_left_right', 'Horizontal Left→Right'), ('horizontal_right_left', 'Horizontal Right→Left'), ('diagonal_ne_sw', 'Diagonal NE→SW'), ('diagonal_nw_se', 'Diagonal NW→SE'), ('diagonal_se_nw', 'Diagonal SE→NW'), ('diagonal_sw_ne', 'Diagonal SW→NE'), ('congestion_time', 'Congestion Time Detector'), ('baliwasan_yjunction', 'Baliwasan Y-Junction')], default='vertical_top_bottom', help_text='Type of detector to use', max_length=50),
        ),
        migrations.AlterField(
            model_name='processingprofile',
            name='enable_congestion_detection',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='processingprofile',
            name='road_type',
            field=models.CharField(choices=[('highway', 'Highway'), ('intersection', 'Intersection'), ('urban', 'Urban Street'), ('generic', 'Generic')], default='generic', max_length=50),
        ),
    ]
