# Generated by Django 4.2.23 on 2026-01-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trapickapp', '0002_remove_processingprofile_config_parameters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingprofile',
            name='config_parameters',
            field=models.JSONField(blank=True, default=dict, help_text='JSON configuration parameters for this processing profile'),
        ),
    ]
